services:
  app:
    image: bootstrap-nextjs-app
    container_name: bootstrap-nextjs-app
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ..:/app
      - /app/node_modules
    command: yarn dev